CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Departments" (
    "DeptId" text NOT NULL,
    "DeptName" text NOT NULL,
    "Location" text NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("DeptId")
);

CREATE TABLE "HospitalTimeSlots" (
    "SlotId" integer NOT NULL,
    "SlotCode" text NOT NULL,
    "SlotName" text NOT NULL,
    "DefaultTime" interval NOT NULL,
    "OffsetMinutes" integer NOT NULL,
    CONSTRAINT "PK_HospitalTimeSlots" PRIMARY KEY ("SlotId")
);

CREATE TABLE "Staffs" (
    "StaffId" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Name" text NOT NULL,
    "IdCard" text NOT NULL,
    "Phone" text NOT NULL,
    "RoleType" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "DeptCode" text NOT NULL,
    CONSTRAINT "PK_Staffs" PRIMARY KEY ("StaffId"),
    CONSTRAINT "FK_Staffs_Departments_DeptCode" FOREIGN KEY ("DeptCode") REFERENCES "Departments" ("DeptId") ON DELETE CASCADE
);

CREATE TABLE "Wards" (
    "WardId" text NOT NULL,
    "DeptId" text NOT NULL,
    "DepartmentDeptId" text,
    CONSTRAINT "PK_Wards" PRIMARY KEY ("WardId"),
    CONSTRAINT "FK_Wards_Departments_DepartmentDeptId" FOREIGN KEY ("DepartmentDeptId") REFERENCES "Departments" ("DeptId")
);

CREATE TABLE "Doctors" (
    "StaffId" text NOT NULL,
    "Title" text NOT NULL,
    "PrescriptionAuthLevel" text NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("StaffId"),
    CONSTRAINT "FK_Doctors_Staffs_StaffId" FOREIGN KEY ("StaffId") REFERENCES "Staffs" ("StaffId") ON DELETE CASCADE
);

CREATE TABLE "Nurses" (
    "StaffId" text NOT NULL,
    "NurseRank" text NOT NULL,
    CONSTRAINT "PK_Nurses" PRIMARY KEY ("StaffId"),
    CONSTRAINT "FK_Nurses_Staffs_StaffId" FOREIGN KEY ("StaffId") REFERENCES "Staffs" ("StaffId") ON DELETE CASCADE
);

CREATE TABLE "Beds" (
    "BedId" text NOT NULL,
    "WardId" text NOT NULL,
    "Status" text NOT NULL,
    CONSTRAINT "PK_Beds" PRIMARY KEY ("BedId"),
    CONSTRAINT "FK_Beds_Wards_WardId" FOREIGN KEY ("WardId") REFERENCES "Wards" ("WardId") ON DELETE CASCADE
);

CREATE TABLE "Patients" (
    "PatientId" text NOT NULL,
    "Name" text NOT NULL,
    "Gender" text NOT NULL,
    "IdCard" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "Age" integer NOT NULL,
    "Weight" real NOT NULL,
    "Status" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "NursingGrade" integer NOT NULL,
    "BedId" text NOT NULL,
    "AttendingDoctorId" text NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("PatientId"),
    CONSTRAINT "FK_Patients_Beds_BedId" FOREIGN KEY ("BedId") REFERENCES "Beds" ("BedId") ON DELETE CASCADE,
    CONSTRAINT "FK_Patients_Doctors_AttendingDoctorId" FOREIGN KEY ("AttendingDoctorId") REFERENCES "Doctors" ("StaffId") ON DELETE CASCADE
);

CREATE TABLE "MedicalOrders" (
    "OrderId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" text NOT NULL,
    "DoctorId" text NOT NULL,
    "NurseId" text,
    "CreateTime" timestamp with time zone NOT NULL,
    "PlantEndTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "OrderType" text NOT NULL,
    "Status" text NOT NULL,
    "IsLongTerm" boolean NOT NULL,
    CONSTRAINT "PK_MedicalOrders" PRIMARY KEY ("OrderId"),
    CONSTRAINT "FK_MedicalOrders_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("StaffId") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicalOrders_Nurses_NurseId" FOREIGN KEY ("NurseId") REFERENCES "Nurses" ("StaffId"),
    CONSTRAINT "FK_MedicalOrders_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("PatientId") ON DELETE CASCADE
);

CREATE TABLE "InspectionOrders" (
    "OrderId" bigint NOT NULL,
    "ItemCode" text NOT NULL,
    "RisLisId" text NOT NULL,
    "Location" text NOT NULL,
    "AppointmentTime" timestamp with time zone,
    "AppointmentPlace" text NOT NULL,
    "Precautions" text NOT NULL,
    "CheckStartTime" timestamp with time zone,
    "CheckEndTime" timestamp with time zone,
    "BackToWardTime" timestamp with time zone,
    "ReportTime" timestamp with time zone,
    "ReportId" text NOT NULL,
    CONSTRAINT "PK_InspectionOrders" PRIMARY KEY ("OrderId"),
    CONSTRAINT "FK_InspectionOrders_MedicalOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "MedicalOrders" ("OrderId") ON DELETE CASCADE
);

CREATE TABLE "MedicationOrders" (
    "OrderId" bigint NOT NULL,
    "DrugId" text NOT NULL,
    "Dosage" text NOT NULL,
    "UsageRoute" text NOT NULL,
    "IsDynamicUsage" boolean NOT NULL,
    "FreqCode" text NOT NULL,
    "StartTime" timestamp with time zone,
    "TimingStrategy" text NOT NULL,
    "SpecificExecutionTime" timestamp with time zone,
    "SmartSlotsMask" integer NOT NULL,
    "IntervalDays" integer NOT NULL,
    CONSTRAINT "PK_MedicationOrders" PRIMARY KEY ("OrderId"),
    CONSTRAINT "FK_MedicationOrders_MedicalOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "MedicalOrders" ("OrderId") ON DELETE CASCADE
);

CREATE TABLE "OperationOrders" (
    "OrderId" bigint NOT NULL,
    "OpId" text NOT NULL,
    "Normal" boolean NOT NULL,
    "FrequencyType" text NOT NULL,
    "FrequencyValue" text NOT NULL,
    CONSTRAINT "PK_OperationOrders" PRIMARY KEY ("OrderId"),
    CONSTRAINT "FK_OperationOrders_MedicalOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "MedicalOrders" ("OrderId") ON DELETE CASCADE
);

CREATE TABLE "SurgicalOrders" (
    "OrderId" bigint NOT NULL,
    "SurgeryName" text NOT NULL,
    "ScheduleTime" timestamp with time zone NOT NULL,
    "AnesthesiaType" text NOT NULL,
    "IncisionSite" text NOT NULL,
    "RequiredMeds" jsonb NOT NULL,
    "NeedBloodPrep" boolean NOT NULL,
    "HasImplants" boolean NOT NULL,
    "PrepProgress" real NOT NULL,
    "PrepStatus" text NOT NULL,
    CONSTRAINT "PK_SurgicalOrders" PRIMARY KEY ("OrderId"),
    CONSTRAINT "FK_SurgicalOrders_MedicalOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "MedicalOrders" ("OrderId") ON DELETE CASCADE
);

CREATE TABLE "InspectionReports" (
    "ReportId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" bigint NOT NULL,
    "PatientId" text NOT NULL,
    "RisLisId" text NOT NULL,
    "ReportTime" timestamp with time zone NOT NULL,
    "ReportStatus" text NOT NULL,
    "Findings" text NOT NULL,
    "Impression" text NOT NULL,
    "AttachmentUrl" text NOT NULL,
    "ReviewerId" text NOT NULL,
    "ReportSource" text NOT NULL,
    CONSTRAINT "PK_InspectionReports" PRIMARY KEY ("ReportId"),
    CONSTRAINT "FK_InspectionReports_InspectionOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "InspectionOrders" ("OrderId") ON DELETE CASCADE,
    CONSTRAINT "FK_InspectionReports_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("PatientId") ON DELETE CASCADE
);

CREATE INDEX "IX_Beds_WardId" ON "Beds" ("WardId");

CREATE INDEX "IX_InspectionReports_OrderId" ON "InspectionReports" ("OrderId");

CREATE INDEX "IX_InspectionReports_PatientId" ON "InspectionReports" ("PatientId");

CREATE INDEX "IX_MedicalOrders_DoctorId" ON "MedicalOrders" ("DoctorId");

CREATE INDEX "IX_MedicalOrders_NurseId" ON "MedicalOrders" ("NurseId");

CREATE INDEX "IX_MedicalOrders_PatientId" ON "MedicalOrders" ("PatientId");

CREATE INDEX "IX_Patients_AttendingDoctorId" ON "Patients" ("AttendingDoctorId");

CREATE INDEX "IX_Patients_BedId" ON "Patients" ("BedId");

CREATE INDEX "IX_Staffs_DeptCode" ON "Staffs" ("DeptCode");

CREATE INDEX "IX_Wards_DepartmentDeptId" ON "Wards" ("DepartmentDeptId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251206035444_RegisterAllTables', '10.0.0');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251206042702_AddNursingModule', '10.0.0');

COMMIT;

START TRANSACTION;
CREATE TABLE "ExecutionTasks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" bigint NOT NULL,
    "PatientId" text NOT NULL,
    "PlannedStartTime" timestamp with time zone NOT NULL,
    "ActualStartTime" timestamp with time zone,
    "ActualEndTime" timestamp with time zone,
    "ExecutorStaffId" text,
    "Status" text NOT NULL,
    "DataPayload" text NOT NULL,
    "ExceptionReason" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExecutionTasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExecutionTasks_MedicalOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "MedicalOrders" ("OrderId") ON DELETE CASCADE,
    CONSTRAINT "FK_ExecutionTasks_Nurses_ExecutorStaffId" FOREIGN KEY ("ExecutorStaffId") REFERENCES "Nurses" ("StaffId"),
    CONSTRAINT "FK_ExecutionTasks_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("PatientId") ON DELETE CASCADE
);

CREATE TABLE "NursingCareNotes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" text NOT NULL,
    "RecorderNurseId" text NOT NULL,
    "RecordTime" timestamp with time zone NOT NULL,
    "Consciousness" text NOT NULL,
    "PupilLeft" text NOT NULL,
    "PupilRight" text NOT NULL,
    "SkinCondition" text NOT NULL,
    "PipeCareData" jsonb NOT NULL,
    "IntakeVolume" numeric NOT NULL,
    "IntakeType" text NOT NULL,
    "OutputVolume" numeric NOT NULL,
    "OutputType" text NOT NULL,
    "Content" text NOT NULL,
    "HealthEducation" text NOT NULL,
    "IsAmended" boolean NOT NULL,
    "ParentAmendId" bigint,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NursingCareNotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NursingCareNotes_Nurses_RecorderNurseId" FOREIGN KEY ("RecorderNurseId") REFERENCES "Nurses" ("StaffId") ON DELETE CASCADE,
    CONSTRAINT "FK_NursingCareNotes_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("PatientId") ON DELETE CASCADE
);

CREATE TABLE "ShiftTypes" (
    "ShiftId" text NOT NULL,
    "ShiftName" text NOT NULL,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    CONSTRAINT "PK_ShiftTypes" PRIMARY KEY ("ShiftId")
);

CREATE TABLE "VitalSignsRecords" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" text NOT NULL,
    "RecorderNurseId" text NOT NULL,
    "RecordTime" timestamp with time zone NOT NULL,
    "Temperature" numeric NOT NULL,
    "TempType" text NOT NULL,
    "Pulse" integer NOT NULL,
    "Respiration" integer NOT NULL,
    "SysBp" integer NOT NULL,
    "DiaBp" integer NOT NULL,
    "Spo2" numeric NOT NULL,
    "PainScore" integer NOT NULL,
    "Weight" numeric NOT NULL,
    "Intervention" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_VitalSignsRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VitalSignsRecords_Nurses_RecorderNurseId" FOREIGN KEY ("RecorderNurseId") REFERENCES "Nurses" ("StaffId") ON DELETE CASCADE,
    CONSTRAINT "FK_VitalSignsRecords_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("PatientId") ON DELETE CASCADE
);

CREATE TABLE "NurseRosters" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StaffId" text NOT NULL,
    "WardId" text NOT NULL,
    "ShiftId" text NOT NULL,
    "WorkDate" date NOT NULL,
    "Status" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NurseRosters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NurseRosters_Nurses_StaffId" FOREIGN KEY ("StaffId") REFERENCES "Nurses" ("StaffId") ON DELETE CASCADE,
    CONSTRAINT "FK_NurseRosters_ShiftTypes_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES "ShiftTypes" ("ShiftId") ON DELETE CASCADE,
    CONSTRAINT "FK_NurseRosters_Wards_WardId" FOREIGN KEY ("WardId") REFERENCES "Wards" ("WardId") ON DELETE CASCADE
);

CREATE INDEX "IX_ExecutionTasks_ExecutorStaffId" ON "ExecutionTasks" ("ExecutorStaffId");

CREATE INDEX "IX_ExecutionTasks_OrderId" ON "ExecutionTasks" ("OrderId");

CREATE INDEX "IX_ExecutionTasks_PatientId" ON "ExecutionTasks" ("PatientId");

CREATE INDEX "IX_NurseRosters_ShiftId" ON "NurseRosters" ("ShiftId");

CREATE INDEX "IX_NurseRosters_StaffId" ON "NurseRosters" ("StaffId");

CREATE INDEX "IX_NurseRosters_WardId" ON "NurseRosters" ("WardId");

CREATE INDEX "IX_NursingCareNotes_PatientId" ON "NursingCareNotes" ("PatientId");

CREATE INDEX "IX_NursingCareNotes_RecorderNurseId" ON "NursingCareNotes" ("RecorderNurseId");

CREATE INDEX "IX_VitalSignsRecords_PatientId" ON "VitalSignsRecords" ("PatientId");

CREATE INDEX "IX_VitalSignsRecords_RecorderNurseId" ON "VitalSignsRecords" ("RecorderNurseId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251206043325_addnurseTables', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Doctors" DROP CONSTRAINT "FK_Doctors_Staffs_StaffId";

ALTER TABLE "Nurses" DROP CONSTRAINT "FK_Nurses_Staffs_StaffId";

ALTER TABLE "Staffs" DROP CONSTRAINT "PK_Staffs";

ALTER TABLE "Staffs" RENAME COLUMN "StaffId" TO "EmployeeNumber";

ALTER TABLE "Nurses" RENAME COLUMN "StaffId" TO "Id";

ALTER TABLE "Doctors" RENAME COLUMN "StaffId" TO "Id";

ALTER TABLE "Staffs" ADD "Id" text NOT NULL DEFAULT '';

ALTER TABLE "Staffs" ADD "CreateTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Staffs" ADD CONSTRAINT "PK_Staffs" PRIMARY KEY ("Id");

ALTER TABLE "Doctors" ADD CONSTRAINT "FK_Doctors_Staffs_Id" FOREIGN KEY ("Id") REFERENCES "Staffs" ("Id") ON DELETE CASCADE;

ALTER TABLE "Nurses" ADD CONSTRAINT "FK_Nurses_Staffs_Id" FOREIGN KEY ("Id") REFERENCES "Staffs" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251206061325_UpdateStaffModel', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "ExecutionTasks" DROP CONSTRAINT "FK_ExecutionTasks_MedicalOrders_OrderId";

ALTER TABLE "InspectionOrders" DROP CONSTRAINT "FK_InspectionOrders_MedicalOrders_OrderId";

ALTER TABLE "MedicationOrders" DROP CONSTRAINT "FK_MedicationOrders_MedicalOrders_OrderId";

ALTER TABLE "OperationOrders" DROP CONSTRAINT "FK_OperationOrders_MedicalOrders_OrderId";

ALTER TABLE "SurgicalOrders" DROP CONSTRAINT "FK_SurgicalOrders_MedicalOrders_OrderId";

ALTER TABLE "MedicalOrders" DROP CONSTRAINT "PK_MedicalOrders";

ALTER TABLE "HospitalTimeSlots" DROP CONSTRAINT "PK_HospitalTimeSlots";

ALTER TABLE "SurgicalOrders" RENAME COLUMN "OrderId" TO "Id";

ALTER TABLE "OperationOrders" RENAME COLUMN "OrderId" TO "Id";

ALTER TABLE "MedicationOrders" RENAME COLUMN "OrderId" TO "Id";

ALTER TABLE "InspectionOrders" RENAME COLUMN "OrderId" TO "Id";

ALTER TABLE "MedicalOrders" ALTER COLUMN "OrderId" DROP IDENTITY;

ALTER TABLE "MedicalOrders" ADD "Id" bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "HospitalTimeSlots" ADD "Id" integer GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "HospitalTimeSlots" ADD "CreateTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "MedicalOrders" ADD CONSTRAINT "PK_MedicalOrders" PRIMARY KEY ("Id");

ALTER TABLE "HospitalTimeSlots" ADD CONSTRAINT "PK_HospitalTimeSlots" PRIMARY KEY ("Id");

ALTER TABLE "ExecutionTasks" ADD CONSTRAINT "FK_ExecutionTasks_MedicalOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE;

ALTER TABLE "InspectionOrders" ADD CONSTRAINT "FK_InspectionOrders_MedicalOrders_Id" FOREIGN KEY ("Id") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE;

ALTER TABLE "MedicationOrders" ADD CONSTRAINT "FK_MedicationOrders_MedicalOrders_Id" FOREIGN KEY ("Id") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE;

ALTER TABLE "OperationOrders" ADD CONSTRAINT "FK_OperationOrders_MedicalOrders_Id" FOREIGN KEY ("Id") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE;

ALTER TABLE "SurgicalOrders" ADD CONSTRAINT "FK_SurgicalOrders_MedicalOrders_Id" FOREIGN KEY ("Id") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251206170056_UpdateHospitalTimeSlotsTable', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "ExecutionTasks" DROP CONSTRAINT "FK_ExecutionTasks_MedicalOrders_OrderId";

ALTER TABLE "Wards" DROP CONSTRAINT "FK_Wards_Departments_DepartmentDeptId";

DROP INDEX "IX_Wards_DepartmentDeptId";

ALTER TABLE "Wards" DROP COLUMN "DepartmentDeptId";

ALTER TABLE "MedicalOrders" DROP COLUMN "OrderId";

ALTER TABLE "HospitalTimeSlots" DROP COLUMN "SlotId";

ALTER TABLE "Wards" RENAME COLUMN "DeptId" TO "DepartmentId";

ALTER TABLE "Wards" RENAME COLUMN "WardId" TO "Id";

ALTER TABLE "ShiftTypes" RENAME COLUMN "ShiftId" TO "Id";

ALTER TABLE "Patients" RENAME COLUMN "PatientId" TO "Id";

ALTER TABLE "InspectionReports" RENAME COLUMN "ReportId" TO "Id";

ALTER TABLE "ExecutionTasks" RENAME COLUMN "OrderId" TO "MedicalOrderId";

ALTER INDEX "IX_ExecutionTasks_OrderId" RENAME TO "IX_ExecutionTasks_MedicalOrderId";

ALTER TABLE "Departments" RENAME COLUMN "DeptId" TO "Id";

ALTER TABLE "Beds" RENAME COLUMN "BedId" TO "Id";

ALTER TABLE "Wards" ADD "CreateTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "ShiftTypes" ADD "CreateTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Patients" ADD "CreateTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "InspectionReports" ALTER COLUMN "ReviewerId" DROP NOT NULL;


                ALTER TABLE "InspectionReports" 
                ALTER COLUMN "ReportStatus" TYPE integer 
                USING (CASE 
                    WHEN "ReportStatus" = '1' OR "ReportStatus" = 'Pending' THEN 1
                    WHEN "ReportStatus" = '2' OR "ReportStatus" = 'Completed' THEN 2
                    ELSE 1
                END)::integer;
            


                ALTER TABLE "InspectionReports" 
                ALTER COLUMN "ReportSource" TYPE integer 
                USING (CASE 
                    WHEN "ReportSource" = '1' OR "ReportSource" = 'RIS' THEN 1
                    WHEN "ReportSource" = '2' OR "ReportSource" = 'LIS' THEN 2
                    ELSE 1
                END)::integer;
            

ALTER TABLE "InspectionReports" ALTER COLUMN "Impression" DROP NOT NULL;

ALTER TABLE "InspectionReports" ALTER COLUMN "Findings" DROP NOT NULL;

ALTER TABLE "InspectionReports" ALTER COLUMN "AttachmentUrl" DROP NOT NULL;

ALTER TABLE "InspectionReports" ADD "CreateTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "InspectionOrders" ALTER COLUMN "ReportId" DROP NOT NULL;

ALTER TABLE "InspectionOrders" ALTER COLUMN "Precautions" DROP NOT NULL;

ALTER TABLE "InspectionOrders" ALTER COLUMN "AppointmentPlace" DROP NOT NULL;

ALTER TABLE "InspectionOrders" ADD "InspectionStatus" integer NOT NULL DEFAULT 0;

ALTER TABLE "InspectionOrders" ADD "Source" integer NOT NULL DEFAULT 0;

ALTER TABLE "HospitalTimeSlots" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "ExecutionTasks" ADD "IsRolledBack" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Departments" ADD "CreateTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Beds" ADD "CreateTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

CREATE INDEX "IX_Wards_DepartmentId" ON "Wards" ("DepartmentId");

CREATE INDEX "IX_InspectionReports_ReviewerId" ON "InspectionReports" ("ReviewerId");

ALTER TABLE "ExecutionTasks" ADD CONSTRAINT "FK_ExecutionTasks_MedicalOrders_MedicalOrderId" FOREIGN KEY ("MedicalOrderId") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE;

ALTER TABLE "InspectionReports" ADD CONSTRAINT "FK_InspectionReports_Doctors_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "Doctors" ("Id");

ALTER TABLE "Wards" ADD CONSTRAINT "FK_Wards_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251207062341_Updatefirsttry', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "MedicationOrders" ALTER COLUMN "DrugId" TYPE character varying(50);

ALTER TABLE "ExecutionTasks" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "ExecutionTasks" ADD "LastModifiedAt" timestamp with time zone;

CREATE TABLE "BarcodeIndexes" (
    "Id" text NOT NULL,
    "TableName" text NOT NULL,
    "RecordId" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BarcodeIndexes" PRIMARY KEY ("Id")
);

CREATE TABLE "Drugs" (
    "Id" character varying(50) NOT NULL,
    "GenericName" character varying(200) NOT NULL,
    "TradeName" character varying(200),
    "Manufacturer" character varying(200),
    "Specification" character varying(100) NOT NULL,
    "DosageForm" character varying(50) NOT NULL,
    "PackageSpec" character varying(100),
    "AtcCode" character varying(20),
    "Category" character varying(100),
    "AdministrationRoute" character varying(50) NOT NULL,
    "UnitPrice" numeric(10,4) NOT NULL,
    "PriceUnit" character varying(20) NOT NULL,
    "IsPrescriptionOnly" boolean NOT NULL,
    "IsNarcotic" boolean NOT NULL,
    "IsPsychotropic" boolean NOT NULL,
    "IsAntibiotic" boolean NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Indications" character varying(1000),
    "Contraindications" character varying(1000),
    "DosageInstructions" character varying(500),
    "SideEffects" character varying(1000),
    "StorageConditions" character varying(200),
    "ShelfLifeMonths" integer,
    "ApprovalNumber" character varying(50),
    "Remarks" character varying(500),
    "CreateTime" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeleteTime" timestamp with time zone,
    CONSTRAINT "PK_Drugs" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_MedicationOrders_DrugId" ON "MedicationOrders" ("DrugId");

ALTER TABLE "MedicationOrders" ADD CONSTRAINT "FK_MedicationOrders_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES "Drugs" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251209090946_AddBarcodeIndexTable', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "BarcodeIndexes" ADD "ImageGeneratedAt" timestamp with time zone;

ALTER TABLE "BarcodeIndexes" ADD "ImageMimeType" text;

ALTER TABLE "BarcodeIndexes" ADD "ImagePath" text;

ALTER TABLE "BarcodeIndexes" ADD "ImageSize" bigint;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251209092608_AddBarcodeImageFields', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "SurgicalOrders" DROP COLUMN "HasImplants";

ALTER TABLE "SurgicalOrders" DROP COLUMN "NeedBloodPrep";

ALTER TABLE "SurgicalOrders" ALTER COLUMN "RequiredMeds" DROP NOT NULL;

ALTER TABLE "SurgicalOrders" ADD "RequiredOperation" text;

ALTER TABLE "SurgicalOrders" ADD "RequiredTalk" text;

ALTER TABLE "MedicationOrders" ALTER COLUMN "DrugId" TYPE character varying(50);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251209092841_UpdateSurgicalOrderSchema', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "ExecutionTasks" ADD "Category" integer NOT NULL DEFAULT 0;

ALTER TABLE "ExecutionTasks" ADD "CompleterNurseId" text;

ALTER TABLE "ExecutionTasks" ADD "ResultPayload" text;

CREATE INDEX "IX_ExecutionTasks_CompleterNurseId" ON "ExecutionTasks" ("CompleterNurseId");

ALTER TABLE "ExecutionTasks" ADD CONSTRAINT "FK_ExecutionTasks_Nurses_CompleterNurseId" FOREIGN KEY ("CompleterNurseId") REFERENCES "Nurses" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251210085131_AddExecutionTaskNewProperties', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "MedicationOrders" DROP CONSTRAINT "FK_MedicationOrders_Drugs_DrugId";

ALTER TABLE "MedicationOrders" DROP COLUMN "Dosage";


                ALTER TABLE "MedicationOrders" 
                ALTER COLUMN "UsageRoute" 
                TYPE integer 
                USING CASE "UsageRoute"
                    WHEN '口服' THEN 1          -- PO
                    WHEN '外用涂抹' THEN 2      -- Topical
                    WHEN '外用/涂抹' THEN 2     -- Topical (变体)
                    WHEN '肌肉注射' THEN 10     -- IM
                    WHEN '皮下注射' THEN 11     -- SC
                    WHEN '静脉推注' THEN 12     -- IVP
                    WHEN '静脉滴注' THEN 20     -- IVGTT
                    WHEN '鼻导管吸氧' THEN 21   -- Inhalation
                    WHEN '吸氧' THEN 21         -- Inhalation (简化形式)
                    WHEN '皮试' THEN 30         -- ST
                    ELSE 1                      -- 默认为 PO (口服)
                END;
            

ALTER TABLE "MedicationOrders" ALTER COLUMN "DrugId" DROP NOT NULL;

CREATE TABLE "MedicationOrderItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MedicationOrderId" bigint NOT NULL,
    "DrugId" character varying(50) NOT NULL,
    "Dosage" text NOT NULL,
    "Note" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MedicationOrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicationOrderItems_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES "Drugs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicationOrderItems_MedicationOrders_MedicationOrderId" FOREIGN KEY ("MedicationOrderId") REFERENCES "MedicationOrders" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MedicationOrderItems_DrugId" ON "MedicationOrderItems" ("DrugId");

CREATE INDEX "IX_MedicationOrderItems_MedicationOrderId" ON "MedicationOrderItems" ("MedicationOrderId");

ALTER TABLE "MedicationOrders" ADD CONSTRAINT "FK_MedicationOrders_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES "Drugs" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251210104232_UpdateMedicationOrderStructure', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "MedicationOrders" DROP CONSTRAINT "FK_MedicationOrders_Drugs_DrugId";

DROP INDEX "IX_MedicationOrders_DrugId";

ALTER TABLE "MedicationOrders" DROP COLUMN "DrugId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251210114528_RemoveDrugIdFromMedicationOrder', '10.0.0');

COMMIT;

