-- 没有加medicaloeder备注
-- 1. Departments
CREATE TABLE "Departments" (
    "Id" text NOT NULL,
    "DeptName" text NOT NULL,
    "Location" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

-- 2. Staffs (Base)
CREATE TABLE "Staffs" (
    "Id" text NOT NULL,
    "EmployeeNumber" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Name" text NOT NULL,
    "IdCard" text NOT NULL,
    "Phone" text NOT NULL,
    "RoleType" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "DeptCode" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Staffs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Staffs_Departments_DeptCode" FOREIGN KEY ("DeptCode") REFERENCES "Departments" ("Id") ON DELETE CASCADE
);

-- 3. Doctors (Derived)
CREATE TABLE "Doctors" (
    "Id" text NOT NULL,
    "Title" text NOT NULL,
    "PrescriptionAuthLevel" text NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Doctors_Staffs_Id" FOREIGN KEY ("Id") REFERENCES "Staffs" ("Id") ON DELETE CASCADE
);

-- 4. Nurses (Derived)
CREATE TABLE "Nurses" (
    "Id" text NOT NULL,
    "NurseRank" text NOT NULL,
    CONSTRAINT "PK_Nurses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Nurses_Staffs_Id" FOREIGN KEY ("Id") REFERENCES "Staffs" ("Id") ON DELETE CASCADE
);

-- 5. Wards
CREATE TABLE "Wards" (
    "Id" text NOT NULL,
    "DepartmentId" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Wards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Wards_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE CASCADE
);

-- 6. Beds
CREATE TABLE "Beds" (
    "Id" text NOT NULL,
    "WardId" text NOT NULL,
    "Status" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Beds" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Beds_Wards_WardId" FOREIGN KEY ("WardId") REFERENCES "Wards" ("Id") ON DELETE CASCADE
);

-- 7. Patients
CREATE TABLE "Patients" (
    "Id" text NOT NULL,
    "Name" text NOT NULL,
    "Gender" text NOT NULL,
    "IdCard" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "Age" integer NOT NULL,
    "Weight" real NOT NULL,
    "Status" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "NursingGrade" integer NOT NULL,
    "BedId" text NOT NULL,
    "AttendingDoctorId" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Patients_Beds_BedId" FOREIGN KEY ("BedId") REFERENCES "Beds" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Patients_Doctors_AttendingDoctorId" FOREIGN KEY ("AttendingDoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE
);

-- 8. Drugs
CREATE TABLE "Drugs" (
    "Id" character varying(50) NOT NULL,
    "GenericName" character varying(200) NOT NULL,
    "TradeName" character varying(200),
    "Manufacturer" character varying(200),
    "Specification" character varying(100) NOT NULL,
    "DosageForm" character varying(50) NOT NULL,
    "PackageSpec" character varying(100),
    "AtcCode" character varying(20),
    "Category" character varying(100),
    "AdministrationRoute" character varying(50) NOT NULL,
    "UnitPrice" numeric(10,4) NOT NULL,
    "PriceUnit" character varying(20) NOT NULL,
    "IsPrescriptionOnly" boolean NOT NULL,
    "IsNarcotic" boolean NOT NULL,
    "IsPsychotropic" boolean NOT NULL,
    "IsAntibiotic" boolean NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Indications" character varying(1000),
    "Contraindications" character varying(1000),
    "DosageInstructions" character varying(500),
    "SideEffects" character varying(1000),
    "StorageConditions" character varying(200),
    "ShelfLifeMonths" integer,
    "ApprovalNumber" character varying(50),
    "Remarks" character varying(500),
    "IsDeleted" boolean NOT NULL,
    "DeleteTime" timestamp with time zone,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Drugs" PRIMARY KEY ("Id")
);

-- 9. HospitalTimeSlots
CREATE TABLE "HospitalTimeSlots" (
    "Id" integer NOT NULL,
    "SlotCode" text NOT NULL,
    "SlotName" text NOT NULL,
    "DefaultTime" interval NOT NULL,
    "OffsetMinutes" integer NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HospitalTimeSlots" PRIMARY KEY ("Id")
);

-- 10. MedicalOrders (Base)
CREATE TABLE "MedicalOrders" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" text NOT NULL,
    "DoctorId" text NOT NULL,
    "NurseId" text,
    "PlantEndTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "OrderType" text NOT NULL,
    "Status" text NOT NULL,
    "IsLongTerm" boolean NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MedicalOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicalOrders_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicalOrders_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicalOrders_Nurses_NurseId" FOREIGN KEY ("NurseId") REFERENCES "Nurses" ("Id")
);

-- 11. MedicationOrders (Derived)
CREATE TABLE "MedicationOrders" (
    "Id" bigint NOT NULL,
    "UsageRoute" integer NOT NULL,
    "IsDynamicUsage" boolean NOT NULL,
    "FreqCode" text NOT NULL,
    "StartTime" timestamp with time zone,
    "TimingStrategy" text NOT NULL,
    "SpecificExecutionTime" timestamp with time zone,
    "SmartSlotsMask" integer NOT NULL,
    "IntervalDays" integer NOT NULL,
    CONSTRAINT "PK_MedicationOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicationOrders_MedicalOrders_Id" FOREIGN KEY ("Id") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE
);

-- 12. MedicationOrderItems
CREATE TABLE "MedicationOrderItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MedicalOrderId" bigint NOT NULL,
    "DrugId" character varying(50) NOT NULL,
    "Dosage" text NOT NULL,
    "Note" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MedicationOrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicationOrderItems_MedicalOrders_MedicalOrderId" FOREIGN KEY ("MedicalOrderId") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MedicationOrderItems_Drugs_DrugId" FOREIGN KEY ("DrugId") REFERENCES "Drugs" ("Id") ON DELETE CASCADE
);

-- 13. InspectionOrders (Derived)
CREATE TABLE "InspectionOrders" (
    "Id" bigint NOT NULL,
    "ItemCode" text NOT NULL,
    "RisLisId" text NOT NULL,
    "Location" text NOT NULL,
    "Source" integer NOT NULL,
    "AppointmentTime" timestamp with time zone,
    "AppointmentPlace" text,
    "Precautions" text,
    "CheckStartTime" timestamp with time zone,
    "CheckEndTime" timestamp with time zone,
    "BackToWardTime" timestamp with time zone,
    "ReportTime" timestamp with time zone,
    "ReportId" text,
    "InspectionStatus" integer NOT NULL,
    CONSTRAINT "PK_InspectionOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InspectionOrders_MedicalOrders_Id" FOREIGN KEY ("Id") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE
);

-- 14. OperationOrders (Derived)
CREATE TABLE "OperationOrders" (
    "Id" bigint NOT NULL,
    "OpId" text NOT NULL,
    "Normal" boolean NOT NULL,
    "FrequencyType" text NOT NULL,
    "FrequencyValue" text NOT NULL,
    CONSTRAINT "PK_OperationOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OperationOrders_MedicalOrders_Id" FOREIGN KEY ("Id") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE
);

-- 15. SurgicalOrders (Derived)
CREATE TABLE "SurgicalOrders" (
    "Id" bigint NOT NULL,
    "SurgeryName" text NOT NULL,
    "ScheduleTime" timestamp with time zone NOT NULL,
    "AnesthesiaType" text NOT NULL,
    "IncisionSite" text NOT NULL,
    "RequiredTalk" text,
    "RequiredOperation" text,
    "RequiredMeds" jsonb,
    "PrepProgress" real NOT NULL,
    "PrepStatus" text NOT NULL,
    CONSTRAINT "PK_SurgicalOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SurgicalOrders_MedicalOrders_Id" FOREIGN KEY ("Id") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE
);

-- 16. InspectionReports
CREATE TABLE "InspectionReports" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" bigint NOT NULL,
    "PatientId" text NOT NULL,
    "RisLisId" text NOT NULL,
    "ReportTime" timestamp with time zone NOT NULL,
    "ReportStatus" integer NOT NULL,
    "Findings" text,
    "Impression" text,
    "AttachmentUrl" text,
    "ReviewerId" text,
    "ReportSource" integer NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InspectionReports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InspectionReports_InspectionOrders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "InspectionOrders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InspectionReports_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InspectionReports_Doctors_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "Doctors" ("Id")
);

-- 17. ExecutionTasks
CREATE TABLE "ExecutionTasks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MedicalOrderId" bigint NOT NULL,
    "PatientId" text NOT NULL,
    "Category" integer NOT NULL,
    "PlannedStartTime" timestamp with time zone NOT NULL,
    "ActualStartTime" timestamp with time zone,
    "ExecutorStaffId" text,
    "ActualEndTime" timestamp with time zone,
    "CompleterNurseId" text,
    "Status" text NOT NULL,
    "IsRolledBack" boolean NOT NULL,
    "DataPayload" text NOT NULL,
    "ResultPayload" text,
    "ExceptionReason" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastModifiedAt" timestamp with time zone,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExecutionTasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExecutionTasks_MedicalOrders_MedicalOrderId" FOREIGN KEY ("MedicalOrderId") REFERENCES "MedicalOrders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ExecutionTasks_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ExecutionTasks_Nurses_ExecutorStaffId" FOREIGN KEY ("ExecutorStaffId") REFERENCES "Nurses" ("Id"),
    CONSTRAINT "FK_ExecutionTasks_Nurses_CompleterNurseId" FOREIGN KEY ("CompleterNurseId") REFERENCES "Nurses" ("Id")
);

-- 18. NursingCareNotes
CREATE TABLE "NursingCareNotes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" text NOT NULL,
    "RecorderNurseId" text NOT NULL,
    "RecordTime" timestamp with time zone NOT NULL,
    "Consciousness" text NOT NULL,
    "PupilLeft" text NOT NULL,
    "PupilRight" text NOT NULL,
    "SkinCondition" text NOT NULL,
    "PipeCareData" jsonb NOT NULL,
    "IntakeVolume" numeric NOT NULL,
    "IntakeType" text NOT NULL,
    "OutputVolume" numeric NOT NULL,
    "OutputType" text NOT NULL,
    "Content" text NOT NULL,
    "HealthEducation" text NOT NULL,
    "IsAmended" boolean NOT NULL,
    "ParentAmendId" bigint,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NursingCareNotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NursingCareNotes_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_NursingCareNotes_Nurses_RecorderNurseId" FOREIGN KEY ("RecorderNurseId") REFERENCES "Nurses" ("Id") ON DELETE CASCADE
);

-- 19. ShiftTypes
CREATE TABLE "ShiftTypes" (
    "Id" text NOT NULL,
    "ShiftName" text NOT NULL,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ShiftTypes" PRIMARY KEY ("Id")
);

-- 20. NurseRosters
CREATE TABLE "NurseRosters" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StaffId" text NOT NULL,
    "WardId" text NOT NULL,
    "ShiftId" text NOT NULL,
    "WorkDate" date NOT NULL,
    "Status" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NurseRosters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NurseRosters_Nurses_StaffId" FOREIGN KEY ("StaffId") REFERENCES "Nurses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_NurseRosters_Wards_WardId" FOREIGN KEY ("WardId") REFERENCES "Wards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_NurseRosters_ShiftTypes_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES "ShiftTypes" ("Id") ON DELETE CASCADE
);

-- 21. VitalSignsRecords
CREATE TABLE "VitalSignsRecords" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" text NOT NULL,
    "RecorderNurseId" text NOT NULL,
    "RecordTime" timestamp with time zone NOT NULL,
    "Temperature" numeric NOT NULL,
    "TempType" text NOT NULL,
    "Pulse" integer NOT NULL,
    "Respiration" integer NOT NULL,
    "SysBp" integer NOT NULL,
    "DiaBp" integer NOT NULL,
    "Spo2" numeric NOT NULL,
    "PainScore" integer NOT NULL,
    "Weight" numeric NOT NULL,
    "Intervention" text NOT NULL,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_VitalSignsRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VitalSignsRecords_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VitalSignsRecords_Nurses_RecorderNurseId" FOREIGN KEY ("RecorderNurseId") REFERENCES "Nurses" ("Id") ON DELETE CASCADE
);

-- 22. BarcodeIndexes
CREATE TABLE "BarcodeIndexes" (
    "Id" text NOT NULL,
    "TableName" text NOT NULL,
    "RecordId" text NOT NULL,
    "ImagePath" text,
    "ImageSize" bigint,
    "ImageMimeType" text,
    "ImageGeneratedAt" timestamp with time zone,
    "CreateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BarcodeIndexes" PRIMARY KEY ("Id")
);

-- Indexes
CREATE INDEX "IX_Staffs_DeptCode" ON "Staffs" ("DeptCode");
CREATE INDEX "IX_Wards_DepartmentId" ON "Wards" ("DepartmentId");
CREATE INDEX "IX_Beds_WardId" ON "Beds" ("WardId");
CREATE INDEX "IX_Patients_BedId" ON "Patients" ("BedId");
CREATE INDEX "IX_Patients_AttendingDoctorId" ON "Patients" ("AttendingDoctorId");
CREATE INDEX "IX_MedicalOrders_PatientId" ON "MedicalOrders" ("PatientId");
CREATE INDEX "IX_MedicalOrders_DoctorId" ON "MedicalOrders" ("DoctorId");
CREATE INDEX "IX_MedicalOrders_NurseId" ON "MedicalOrders" ("NurseId");
CREATE INDEX "IX_MedicationOrderItems_MedicalOrderId" ON "MedicationOrderItems" ("MedicalOrderId");
CREATE INDEX "IX_MedicationOrderItems_DrugId" ON "MedicationOrderItems" ("DrugId");
CREATE INDEX "IX_InspectionReports_OrderId" ON "InspectionReports" ("OrderId");
CREATE INDEX "IX_InspectionReports_PatientId" ON "InspectionReports" ("PatientId");
CREATE INDEX "IX_InspectionReports_ReviewerId" ON "InspectionReports" ("ReviewerId");
CREATE INDEX "IX_ExecutionTasks_MedicalOrderId" ON "ExecutionTasks" ("MedicalOrderId");
CREATE INDEX "IX_ExecutionTasks_PatientId" ON "ExecutionTasks" ("PatientId");
CREATE INDEX "IX_ExecutionTasks_ExecutorStaffId" ON "ExecutionTasks" ("ExecutorStaffId");
CREATE INDEX "IX_ExecutionTasks_CompleterNurseId" ON "ExecutionTasks" ("CompleterNurseId");
CREATE INDEX "IX_NursingCareNotes_PatientId" ON "NursingCareNotes" ("PatientId");
CREATE INDEX "IX_NursingCareNotes_RecorderNurseId" ON "NursingCareNotes" ("RecorderNurseId");
CREATE INDEX "IX_NurseRosters_StaffId" ON "NurseRosters" ("StaffId");
CREATE INDEX "IX_NurseRosters_WardId" ON "NurseRosters" ("WardId");
CREATE INDEX "IX_NurseRosters_ShiftId" ON "NurseRosters" ("ShiftId");
CREATE INDEX "IX_VitalSignsRecords_PatientId" ON "VitalSignsRecords" ("PatientId");
CREATE INDEX "IX_VitalSignsRecords_RecorderNurseId" ON "VitalSignsRecords" ("RecorderNurseId");