// <auto-generated />
using System;
using CareFlow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareFlow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206035444_RegisterAllTables")]
    partial class RegisterAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareFlow.Core.Models.Medical.HospitalTimeSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("DefaultTime")
                        .HasColumnType("interval");

                    b.Property<int>("OffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SlotId");

                    b.ToTable("HospitalTimeSlots");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.InspectionReport", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReportId"));

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Impression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RisLisId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReportId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PatientId");

                    b.ToTable("InspectionReports");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.MedicalOrder", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderId"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLongTerm")
                        .HasColumnType("boolean");

                    b.Property<string>("NurseId")
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PlantEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalOrders");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CareFlow.Core.Models.Organization.Department", b =>
                {
                    b.Property<string>("DeptId")
                        .HasColumnType("text");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Organization.Staff", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("text");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdCard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StaffId");

                    b.HasIndex("DeptCode");

                    b.ToTable("Staffs");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CareFlow.Core.Models.Patient.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AttendingDoctorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdCard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NursingGrade")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("PatientId");

                    b.HasIndex("AttendingDoctorId");

                    b.HasIndex("BedId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Space.Bed", b =>
                {
                    b.Property<string>("BedId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BedId");

                    b.HasIndex("WardId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Space.Ward", b =>
                {
                    b.Property<string>("WardId")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentDeptId")
                        .HasColumnType("text");

                    b.Property<string>("DeptId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WardId");

                    b.HasIndex("DepartmentDeptId");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.InspectionOrder", b =>
                {
                    b.HasBaseType("CareFlow.Core.Models.Medical.MedicalOrder");

                    b.Property<string>("AppointmentPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AppointmentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BackToWardTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Precautions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RisLisId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("InspectionOrders", (string)null);
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.MedicationOrder", b =>
                {
                    b.HasBaseType("CareFlow.Core.Models.Medical.MedicalOrder");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrugId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FreqCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDynamicUsage")
                        .HasColumnType("boolean");

                    b.Property<int>("SmartSlotsMask")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SpecificExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimingStrategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsageRoute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("MedicationOrders", (string)null);
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.OperationOrder", b =>
                {
                    b.HasBaseType("CareFlow.Core.Models.Medical.MedicalOrder");

                    b.Property<string>("FrequencyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrequencyValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Normal")
                        .HasColumnType("boolean");

                    b.Property<string>("OpId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("OperationOrders", (string)null);
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.SurgicalOrder", b =>
                {
                    b.HasBaseType("CareFlow.Core.Models.Medical.MedicalOrder");

                    b.Property<string>("AnesthesiaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasImplants")
                        .HasColumnType("boolean");

                    b.Property<string>("IncisionSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NeedBloodPrep")
                        .HasColumnType("boolean");

                    b.Property<float>("PrepProgress")
                        .HasColumnType("real");

                    b.Property<string>("PrepStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredMeds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ScheduleTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SurgeryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("SurgicalOrders", (string)null);
                });

            modelBuilder.Entity("CareFlow.Core.Models.Organization.Doctor", b =>
                {
                    b.HasBaseType("CareFlow.Core.Models.Organization.Staff");

                    b.Property<string>("PrescriptionAuthLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("CareFlow.Core.Models.Organization.Nurse", b =>
                {
                    b.HasBaseType("CareFlow.Core.Models.Organization.Staff");

                    b.Property<string>("NurseRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Nurses", (string)null);
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.InspectionReport", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Medical.InspectionOrder", "InspectionOrder")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareFlow.Core.Models.Patient.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspectionOrder");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.MedicalOrder", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Organization.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareFlow.Core.Models.Organization.Nurse", "Nurse")
                        .WithMany()
                        .HasForeignKey("NurseId");

                    b.HasOne("CareFlow.Core.Models.Patient.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Organization.Staff", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Organization.Department", "Department")
                        .WithMany("StaffList")
                        .HasForeignKey("DeptCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Patient.Patient", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Organization.Doctor", "AttendingDoctor")
                        .WithMany()
                        .HasForeignKey("AttendingDoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareFlow.Core.Models.Space.Bed", "Bed")
                        .WithMany()
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendingDoctor");

                    b.Navigation("Bed");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Space.Bed", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Space.Ward", "Ward")
                        .WithMany("Beds")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Space.Ward", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Organization.Department", "Department")
                        .WithMany("Wards")
                        .HasForeignKey("DepartmentDeptId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.InspectionOrder", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Medical.MedicalOrder", null)
                        .WithOne()
                        .HasForeignKey("CareFlow.Core.Models.Medical.InspectionOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.MedicationOrder", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Medical.MedicalOrder", null)
                        .WithOne()
                        .HasForeignKey("CareFlow.Core.Models.Medical.MedicationOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.OperationOrder", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Medical.MedicalOrder", null)
                        .WithOne()
                        .HasForeignKey("CareFlow.Core.Models.Medical.OperationOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareFlow.Core.Models.Medical.SurgicalOrder", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Medical.MedicalOrder", null)
                        .WithOne()
                        .HasForeignKey("CareFlow.Core.Models.Medical.SurgicalOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareFlow.Core.Models.Organization.Doctor", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Organization.Staff", null)
                        .WithOne()
                        .HasForeignKey("CareFlow.Core.Models.Organization.Doctor", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareFlow.Core.Models.Organization.Nurse", b =>
                {
                    b.HasOne("CareFlow.Core.Models.Organization.Staff", null)
                        .WithOne()
                        .HasForeignKey("CareFlow.Core.Models.Organization.Nurse", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareFlow.Core.Models.Organization.Department", b =>
                {
                    b.Navigation("StaffList");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("CareFlow.Core.Models.Space.Ward", b =>
                {
                    b.Navigation("Beds");
                });
#pragma warning restore 612, 618
        }
    }
}
